# Site settings
title: 자바자바
email: kdy2353@gmail.com
description: "더 나은 개발자로.."
logo_location: "![ee](https://user-images.githubusercontent.com/45562285/49655037-cbfc5300-fa7c-11e8-9858-bede4baed118.PNG)"

#baseurl: "" # the subpath of your site, e.g. /blog/
#url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
kramdown:
  input: GFM

highlighter: rouge

#Other Global Configuration
exclude: ['README.md']

excerpt_separator: <!--more-->

#show the jumbotron header on index page
show_blog_header: true
